App\Webedia\ShopApiPlugin\View\Product\ProductVariantView:
    exclusion_policy: ALL
    xml_root_name: product_variant_view
    properties:
        code:
            expose: true
            type: string
        name:
            expose: true
            type: string
        axis:
            expose: true
            type: array
        nameAxis:
            expose: true
            type: array<string, string>
        idAxis:
            expose: true
            type: array<string, integer>
        price:
            expose: true
            type: App\Webedia\ShopApiPlugin\View\PriceView
        originalPrice:
            expose: true
            type: App\Webedia\ShopApiPlugin\View\PriceView
        images:
            expose: true
            type: array
